'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

export type Property3DData = any;
const dim=(d:any)=>{const f=d.floors||4;const h=d.buildingHeight||f*(d.floorHeight||3);const s=d.buildingArea?Math.sqrt(d.buildingArea):12;return{w:d.footprintWidth||s,dp:d.footprintDepth||s,h,f};};
const pxToWorld=(p:any,a:any,w:number,d:number)=>({x:(p.x/(a.aerialImageWidthPx||1)-0.5)*w,z:(p.y/(a.aerialImageHeightPx||1)-0.5)*d});

export function Property3DViewer({data}:{data:Property3DData}){const ref=useRef<HTMLDivElement|null>(null);const cRef=useRef<any>(null);const [auto,setAuto]=useState(true);const [loading,setLoading]=useState(true);const [err,setErr]=useState<string|null>(null);const [viewBadge,setViewBadge]=useState('Procedural mode'); const d=useMemo(()=>dim(data),[data]);
useEffect(()=>{const el=ref.current;if(!el)return; const scene=new THREE.Scene();scene.background=new THREE.Color('#0b1220'); const r=new THREE.WebGLRenderer({antialias:true});r.outputColorSpace=THREE.SRGBColorSpace;r.shadowMap.enabled=true;el.appendChild(r.domElement);const cam=new THREE.PerspectiveCamera(52,1,0.1,3000);cam.position.set(d.w*2,d.h*1.25,d.dp*2);const ctl=new OrbitControls(cam,r.domElement);cRef.current=ctl;ctl.enableDamping=true;ctl.target.set(0,d.h*0.45,0);scene.add(new THREE.AmbientLight(0xffffff,0.5),new THREE.HemisphereLight(0xc9e2ff,0x263341,0.7),new THREE.DirectionalLight(0xffffff,1));
const dispos:any[]=[];const texs:any[]=[];const add=(o:any)=>scene.add(o);
const mode=data.viewerRealismMode?.sceneMode||'procedural'; const aerial=data.aerialContext||{}; const facade=data.realFacadeTextures||{}; const disableFake=mode!=='procedural'&&(data.viewerRealismMode?.disableFakeSurroundings!==false);
setViewBadge(mode==='real_aerial'?'Real aerial mode':mode==='mixed'?'Mixed mode':mode==='real_aerial_with_osm'?'Real aerial + OSM':'Procedural mode');
const makeGround=async()=>{if((mode==='real_aerial'||mode==='real_aerial_with_osm'||mode==='mixed')&&aerial.aerialImageUrl){try{const t=await new THREE.TextureLoader().loadAsync(aerial.aerialImageUrl);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.anisotropy=r.capabilities.getMaxAnisotropy();texs.push(t);const gw=aerial.aerialWidthMeters||((aerial.aerialImageWidthPx||1024)*(aerial.aerialMetersPerPixel||0.2));const gd=aerial.aerialDepthMeters||((aerial.aerialImageHeightPx||1024)*(aerial.aerialMetersPerPixel||0.2));const g=new THREE.Mesh(new THREE.PlaneGeometry(gw,gd),new THREE.MeshStandardMaterial({map:t}));g.rotation.x=-Math.PI/2;g.rotation.z=THREE.MathUtils.degToRad(aerial.aerialRotationDeg||0);g.receiveShadow=true;add(g);dispos.push(g.geometry,g.material);return {gw,gd};}catch{if(!aerial.allowProceduralFallback){setErr('Aerial image failed to load');}}}
const g=new THREE.Mesh(new THREE.PlaneGeometry(240,240),new THREE.MeshStandardMaterial({color:'#2b3d4f'}));g.rotation.x=-Math.PI/2;add(g);dispos.push(g.geometry,g.material);return {gw:240,gd:240};};
const building=async(ground:any)=>{const root=new THREE.Group(); add(root); let cx=0,cz=0,rot=THREE.MathUtils.degToRad(data.rotationDeg||0),bw=d.w,bd=d.dp;
const fp=aerial.buildingFootprintImagePoints; if(fp&&fp.length===4&&ground){const p=fp.map((q:any)=>pxToWorld(q,aerial,ground.gw,ground.gd)); cx=(p[0].x+p[2].x)/2;cz=(p[0].z+p[2].z)/2; bw=Math.hypot(p[1].x-p[0].x,p[1].z-p[0].z); bd=Math.hypot(p[3].x-p[0].x,p[3].z-p[0].z); rot=Math.atan2(p[1].z-p[0].z,p[1].x-p[0].x);} 
if(data.modelUrl&&/\.(glb|gltf)$/i.test(data.modelUrl)){try{const gltf=await new GLTFLoader().loadAsync(data.modelUrl);gltf.scene.position.set(cx,0,cz);root.add(gltf.scene);setLoading(false);return;}catch{}}
const box=new THREE.Mesh(new THREE.BoxGeometry(bw,d.h,bd),new THREE.MeshStandardMaterial({color:'#cbd5e1'}));box.position.set(cx,d.h/2,cz);box.rotation.y=rot;box.castShadow=true;root.add(box);
const maps=[['facadeRight',facade.facadeRight?.rectifiedImageUrl||facade.facadeRight?.imageUrl||data.facadeRightUrl,bw,d.h,[bw/2+0.03,d.h/2,0],Math.PI/2],['facadeLeft',facade.facadeLeft?.rectifiedImageUrl||facade.facadeLeft?.imageUrl||data.facadeLeftUrl,bw,d.h,[-bw/2-0.03,d.h/2,0],-Math.PI/2],['facadeFront',facade.facadeFront?.rectifiedImageUrl||facade.facadeFront?.imageUrl||data.facadeFrontUrl,bw,d.h,[0,d.h/2,bd/2+0.03],0],['facadeBack',facade.facadeBack?.rectifiedImageUrl||facade.facadeBack?.imageUrl||data.facadeBackUrl,bw,d.h,[0,d.h/2,-bd/2-0.03],Math.PI]] as any[];
for(const m of maps){if(!m[1])continue;try{const t=await new THREE.TextureLoader().loadAsync(m[1]);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.anisotropy=r.capabilities.getMaxAnisotropy();const pl=new THREE.Mesh(new THREE.PlaneGeometry(m[2],m[3]),new THREE.MeshStandardMaterial({map:t}));pl.position.set(m[4][0],m[4][1],m[4][2]);pl.rotation.y=m[5]; if((facade[m[0]]?.flipX)) t.repeat.x=-1; if((facade[m[0]]?.flipY)) t.repeat.y=-1; pl.rotation.z=THREE.MathUtils.degToRad(facade[m[0]]?.rotationDeg||0); root.add(pl); texs.push(t);}catch{}}
root.position.set(cx,0,cz); root.rotation.y=rot; setLoading(false);};
makeGround().then((g)=>{if(!disableFake){const road=new THREE.Mesh(new THREE.PlaneGeometry(200,16),new THREE.MeshStandardMaterial({color:'#1f2937'}));road.rotation.x=-Math.PI/2;road.position.z=-42;add(road);} building(g);});
const rz=()=>{const w=el.clientWidth||1,h=el.clientHeight||1;cam.aspect=w/h;cam.updateProjectionMatrix();r.setSize(w,h)}; const ro=new ResizeObserver(rz);ro.observe(el);rz(); let f=0;const loop=()=>{f=requestAnimationFrame(loop);ctl.autoRotate=auto;ctl.update();r.render(scene,cam)};loop();
(ref.current as any).__cam=cam; (ref.current as any).__ctl=ctl;
return()=>{cancelAnimationFrame(f);ro.disconnect();ctl.dispose();dispos.forEach((x:any)=>x?.dispose?.());texs.forEach((t:any)=>t.dispose?.());r.dispose();el.contains(r.domElement)&&el.removeChild(r.domElement);};
},[data,auto,d]);
const topView=()=>{const cam=(ref.current as any)?.__cam;const ctl=(ref.current as any)?.__ctl;if(!cam||!ctl)return; cam.position.set(0,140,0.01); ctl.target.set(0,0,0);};
const bView=()=>{const cam=(ref.current as any)?.__cam;const ctl=(ref.current as any)?.__ctl;if(!cam||!ctl)return; cam.position.set(d.w*2,d.h*1.2,d.dp*2); ctl.target.set(0,d.h*0.45,0);};
return <div className='relative h-[58vh] min-h-[380px] w-full'><div ref={ref} className='h-full w-full'/><div className='absolute left-3 top-3 rounded bg-slate-900/80 px-3 py-2 text-xs text-white'><div>{viewBadge}</div><div>{data.aerialContext?.aerialAttribution||''}</div></div><div className='absolute bottom-3 right-3 flex gap-2'><button onClick={()=>cRef.current?.reset()} className='rounded bg-white/90 px-3 py-1 text-sm'>Reset</button><button onClick={()=>setAuto(v=>!v)} className='rounded bg-white/90 px-3 py-1 text-sm'>{auto?'Stop rotate':'Auto rotate'}</button><button onClick={topView} className='rounded bg-white/90 px-3 py-1 text-sm'>Top View</button><button onClick={bView} className='rounded bg-white/90 px-3 py-1 text-sm'>Building View</button><button onClick={()=>ref.current?.requestFullscreen?.()} className='rounded bg-white/90 px-3 py-1 text-sm'>Fullscreen</button></div>{loading&&<p className='absolute bottom-3 left-3 rounded bg-slate-900/80 px-3 py-1 text-xs text-white'>Loading…</p>}{err&&<p className='absolute bottom-10 left-3 rounded bg-amber-700/90 px-3 py-1 text-xs text-white'>{err}</p>}</div>
}
